### ISSUE TITLE
house-keeping: discuss merge protocol

### ISSUE THREAD

**Issue by ibixler** [Music-Visualization-MQP/mono-repo#53] opened 2024-11-04 01:31 UTC

**Comment by notsoli** [comment] 2024-11-04 20:33
A PR can only be merged once ALL changes are approved.
PR's can fall into two informal, subjective categories: small or large
- Small changes only need one approval
- Large changes need two approvals
Once all changes are approved, the PR opener can merge without verbal confirmation.

If a problem is identified, it is up to either the approver or PR author to fix the problems. Once the problem is fixed, the PR requires one extra approval (regardless or not if the PR is small or large). If these changes are approved, the PR can be merged. If not, this process repeats.

**Closed** 2024-11-15 17:27 UTC
